/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Registered pricing methods and version.
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price
         * @description Price one instrument with greeks in desk units.
         */
        post: operations["price_api_price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BumpSettingsIn
         * @description Bump sizes for bump-and-revalue greeks.
         */
        BumpSettingsIn: {
            /**
             * Rate Abs
             * @default 0.0001
             */
            rate_abs: number;
            /**
             * Spot Rel
             * @default 0.001
             */
            spot_rel: number;
            /**
             * Time Days
             * @default 1
             */
            time_days: number;
            /**
             * Vol Abs
             * @default 0.001
             */
            vol_abs: number;
        };
        /**
         * DiagnosticsOut
         * @description Diagnostics of a pricing run.
         */
        DiagnosticsOut: {
            /** Details */
            details: {
                [key: string]: number | string;
            };
            /** Method */
            method: string;
            /** Method Label */
            method_label: string;
            /** Model */
            model: string;
            /** Revaluations */
            revaluations: number;
            /**
             * Runtime Ms
             * @description Engine wall-clock time for price and greeks, ms
             */
            runtime_ms: number;
            settings: components["schemas"]["SettingsIn"];
            /** Warnings */
            warnings: string[];
        };
        /**
         * ErrorResponse
         * @description Engine error surfaced to the client.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * EuropeanOptionIn
         * @description European call or put.
         */
        EuropeanOptionIn: {
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            option_type: components["schemas"]["OptionType"];
            /**
             * Quantity
             * @description Units of underlying
             * @default 1
             */
            quantity: number;
            /**
             * Strike
             * @description Strike, in price units
             */
            strike: number;
            /**
             * Type
             * @default european
             * @constant
             */
            type: "european";
        };
        /**
         * Greek
         * @description Supported sensitivities, with their pure-unit definition.
         *
         *     ``V`` is the unit price, ``S`` spot, ``σ`` the implied vol (parallel surface shift), ``r``
         *     the discount zero rate, ``q`` the dividend yield, ``t`` calendar time in years (``τ = T − t``).
         * @enum {string}
         */
        Greek: "delta" | "gamma" | "vega" | "theta" | "rho" | "phi" | "vanna" | "volga" | "charm";
        /**
         * GreekOut
         * @description One greek in desk units.
         */
        GreekOut: {
            key: components["schemas"]["Greek"];
            source: components["schemas"]["GreekSource"];
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /**
         * GreekSource
         * @description How a greek was computed.
         * @enum {string}
         */
        GreekSource: "analytic" | "bump";
        /**
         * GreeksOut
         * @description Greeks in both display modes so the UI can toggle without refetching.
         */
        GreeksOut: {
            /** Cash */
            cash: components["schemas"]["GreekOut"][];
            /** Pure */
            pure: components["schemas"]["GreekOut"][];
        };
        /**
         * HealthResponse
         * @description Liveness probe.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * MarketIn
         * @description Flat market: continuously compounded rates, ACT/365F.
         */
        MarketIn: {
            /**
             * Borrow
             * @description Repo/borrow spread, continuous, decimal
             * @default 0
             */
            borrow: number;
            /**
             * Dividend Yield
             * @description Continuous dividend yield, decimal
             * @default 0
             */
            dividend_yield: number;
            /**
             * Rate
             * @description Discount zero rate, continuous, decimal
             */
            rate: number;
            /** Spot */
            spot: number;
            /**
             * Valuation Date
             * Format: date
             */
            valuation_date: string;
            /**
             * Vol
             * @description Implied volatility, decimal
             */
            vol: number;
        };
        /**
         * MetaResponse
         * @description Static metadata for the UI.
         */
        MetaResponse: {
            /** Methods */
            methods: components["schemas"]["MethodOut"][];
            /** Version */
            version: string;
        };
        /**
         * MethodOut
         * @description A registered pricing method.
         */
        MethodOut: {
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /**
         * ModelIn
         * @description Model selection.
         */
        ModelIn: {
            /**
             * Type
             * @default bsm
             * @constant
             */
            type: "bsm";
        };
        /**
         * OptionType
         * @description Call or put. ``omega`` is +1 for a call and −1 for a put.
         * @enum {string}
         */
        OptionType: "call" | "put";
        /**
         * PriceRequest
         * @description Price one instrument.
         */
        PriceRequest: {
            instrument: components["schemas"]["EuropeanOptionIn"];
            market: components["schemas"]["MarketIn"];
            /**
             * Method
             * @default forward_intrinsic
             */
            method: string;
            /**
             * @default {
             *       "type": "bsm"
             *     }
             */
            model: components["schemas"]["ModelIn"];
            /**
             * @default {
             *       "bumps": {
             *         "rate_abs": 0.0001,
             *         "spot_rel": 0.001,
             *         "time_days": 1,
             *         "vol_abs": 0.001
             *       }
             *     }
             */
            settings: components["schemas"]["SettingsIn"];
        };
        /**
         * PriceResponse
         * @description Price, market-derived quantities, greeks and diagnostics.
         */
        PriceResponse: {
            /** Currency */
            currency: string;
            diagnostics: components["schemas"]["DiagnosticsOut"];
            /** Discount Factor */
            discount_factor: number;
            /** Forward */
            forward: number;
            greeks: components["schemas"]["GreeksOut"];
            /**
             * Pct Notional
             * @description 100 × unit price / spot, %
             */
            pct_notional: number;
            /**
             * Position Value
             * @description quantity × unit price, currency
             */
            position_value: number;
            /**
             * Price
             * @description Unit price, currency
             */
            price: number;
            /**
             * Time To Expiry
             * @description ACT/365F year fraction
             */
            time_to_expiry: number;
        };
        /**
         * SettingsIn
         * @description Numerical settings.
         */
        SettingsIn: {
            /**
             * @default {
             *       "rate_abs": 0.0001,
             *       "spot_rel": 0.001,
             *       "time_days": 1,
             *       "vol_abs": 0.001
             *     }
             */
            bumps: components["schemas"]["BumpSettingsIn"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    price_api_price_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
