/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description The product under every registered method, with convergence and exercise boundary.
         */
        post: operations["compare_api_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heatmap
         * @description Full-revaluation position values over spot × vol shocks, optionally after a time roll.
         */
        post: operations["heatmap_api_heatmap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/implied-vol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Implied Vol
         * @description Flat implied volatility reproducing a unit price (Let's Be Rational), European only.
         */
        post: operations["implied_vol_api_implied_vol_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Registered pricing methods, the products each supports, and version.
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price
         * @description Price one instrument with greeks in desk units.
         */
        post: operations["price_api_price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Profile
         * @description Position value and desk greeks along spot or time (full revaluation at each point).
         *
         *     Numerical methods run at the scenario resolution (``settings.scenario``).
         */
        post: operations["profile_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AmericanOptionIn
         * @description American call or put (exercisable any day up to expiry).
         */
        AmericanOptionIn: {
            /**
             * Currency
             * @default EUR
             */
            currency?: string;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            option_type: components["schemas"]["OptionType"];
            /**
             * Quantity
             * @description Units of underlying
             * @default 1
             */
            quantity?: number;
            /**
             * Strike
             * @description Strike, in price units
             */
            strike: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "american";
        };
        /**
         * BumpSettingsIn
         * @description Bump sizes for bump-and-revalue greeks.
         */
        BumpSettingsIn: {
            /**
             * Rate Abs
             * @default 0.0001
             */
            rate_abs?: number;
            /**
             * Spot Rel
             * @default 0.001
             */
            spot_rel?: number;
            /**
             * Time Days
             * @default 1
             */
            time_days?: number;
            /**
             * Vol Abs
             * @default 0.001
             */
            vol_abs?: number;
        };
        /**
         * CompareRequest
         * @description The same product under every registered method.
         */
        CompareRequest: {
            /**
             * Convergence
             * @default true
             */
            convergence?: boolean;
            pricing: components["schemas"]["PriceRequest"];
        };
        /**
         * CompareResponse
         * @description Methods side by side.
         */
        CompareResponse: {
            boundary?: components["schemas"]["ExerciseBoundary"] | null;
            /** Currency */
            currency: string;
            /**
             * European Price
             * @description Same contract with European exercise (unit, closed form)
             */
            european_price?: number | null;
            /** Methods */
            methods: components["schemas"]["MethodComparison"][];
        };
        /**
         * ConvergencePointOut
         * @description Price at one resolution.
         */
        ConvergencePointOut: {
            /**
             * Price
             * @description Unit price, currency
             */
            price: number;
            /** Resolution */
            resolution: number;
            /** Runtime Ms */
            runtime_ms: number;
        };
        /**
         * CurveIn
         * @description Zero curve with log-linear discount factors between pillars.
         *
         *     Flat before the first pillar; the last forward is extended beyond the last.
         */
        CurveIn: {
            /** Pillars */
            pillars: components["schemas"]["PillarIn"][];
        };
        /**
         * DiagnosticsOut
         * @description Diagnostics of a pricing run.
         */
        DiagnosticsOut: {
            /** Details */
            details: {
                [key: string]: number | string;
            };
            /** Method */
            method: string;
            /** Method Label */
            method_label: string;
            /** Model */
            model: string;
            /** Revaluations */
            revaluations: number;
            /**
             * Runtime Ms
             * @description Engine CPU time for price and greeks, ms
             */
            runtime_ms: number;
            settings: components["schemas"]["SettingsIn"];
            /** Warnings */
            warnings: string[];
        };
        /**
         * DigitalOptionIn
         * @description Cash-or-nothing digital paying ``payout`` per unit if in the money at expiry.
         */
        DigitalOptionIn: {
            /**
             * Currency
             * @default EUR
             */
            currency?: string;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            option_type: components["schemas"]["OptionType"];
            /**
             * Payout
             * @description Cash per unit, currency
             * @default 1
             */
            payout?: number;
            /**
             * Quantity
             * @description Units of underlying
             * @default 1
             */
            quantity?: number;
            /**
             * Strike
             * @description Strike, in price units
             */
            strike: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "digital";
        };
        /**
         * DigitalSettingsIn
         * @description Digital greek smoothing.
         */
        DigitalSettingsIn: {
            /**
             * Spread Width Rel
             * @default 0.01
             */
            spread_width_rel?: number;
        };
        /**
         * DividendIn
         * @description Discrete dividend: ``S → S·(1 − proportional) − cash`` at the ex-date open.
         */
        DividendIn: {
            /**
             * Cash
             * @description Cash per share, currency
             * @default 0
             */
            cash?: number;
            /**
             * Ex Date
             * Format: date
             */
            ex_date: string;
            /**
             * Proportional
             * @description Fraction of spot
             * @default 0
             */
            proportional?: number;
        };
        /**
         * DividendTreatment
         * @description How discrete cash dividends enter the dynamics.
         * @enum {string}
         */
        DividendTreatment: "escrowed" | "spot";
        /**
         * ErrorResponse
         * @description Engine error surfaced to the client.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * EuropeanOptionIn
         * @description European call or put.
         */
        EuropeanOptionIn: {
            /**
             * Currency
             * @default EUR
             */
            currency?: string;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            option_type: components["schemas"]["OptionType"];
            /**
             * Quantity
             * @description Units of underlying
             * @default 1
             */
            quantity?: number;
            /**
             * Strike
             * @description Strike, in price units
             */
            strike: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "european";
        };
        /**
         * ExerciseBoundary
         * @description PDE early-exercise boundary: exercise when spot is beyond ``spot`` at ``days``.
         */
        ExerciseBoundary: {
            /**
             * Days
             * @description Days from the valuation date
             */
            days: number[];
            /**
             * Spot
             * @description Critical spot S*; null where not exercised
             */
            spot: (number | null)[];
        };
        /**
         * Greek
         * @description Supported sensitivities, with their pure-unit definition.
         *
         *     ``V`` is the unit price, ``S`` spot, ``σ`` the implied vol (parallel surface shift), ``r``
         *     the discount zero rate, ``q`` the dividend yield, ``t`` calendar time in years (``τ = T − t``).
         * @enum {string}
         */
        Greek: "delta" | "gamma" | "vega" | "theta" | "rho" | "phi" | "vanna" | "volga" | "charm";
        /**
         * GreekOut
         * @description One greek in desk units.
         */
        GreekOut: {
            key: components["schemas"]["Greek"];
            source: components["schemas"]["GreekSource"];
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /**
         * GreekSource
         * @description How a greek was computed.
         * @enum {string}
         */
        GreekSource: "analytic" | "bump";
        /**
         * GreeksOut
         * @description Greeks in both display modes so the UI can toggle without refetching.
         */
        GreeksOut: {
            /** Cash */
            cash: components["schemas"]["GreekOut"][];
            /** Pure */
            pure: components["schemas"]["GreekOut"][];
        };
        /**
         * HealthResponse
         * @description Liveness probe.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * HeatmapRequest
         * @description Full-revaluation value grid over spot and vol shocks.
         */
        HeatmapRequest: {
            /**
             * Horizon Days
             * @default 0
             */
            horizon_days?: number;
            pricing: components["schemas"]["PriceRequest"];
            /**
             * Spot Range Pct
             * @default 20
             */
            spot_range_pct?: number;
            /**
             * Spot Steps
             * @default 21
             */
            spot_steps?: number;
            /**
             * Vol Range Pts
             * @default 10
             */
            vol_range_pts?: number;
            /**
             * Vol Steps
             * @default 21
             */
            vol_steps?: number;
        };
        /**
         * HeatmapResponse
         * @description Position values on a vol × spot grid (rows: vol shifts). ``null`` = shock out of domain.
         */
        HeatmapResponse: {
            /**
             * Base Value
             * @description Current position value, currency
             */
            base_value: number;
            /** Currency */
            currency: string;
            /** Horizon Days */
            horizon_days: number;
            /**
             * Notional
             * @description quantity × current spot, currency
             */
            notional: number;
            /** Spot Shifts Pct */
            spot_shifts_pct: number[];
            /** Values */
            values: (number | null)[][];
            /** Vol Shifts Pts */
            vol_shifts_pts: number[];
        };
        /**
         * ImpliedVolRequest
         * @description Implied vol from a unit price. ``market.vol`` is ignored.
         */
        ImpliedVolRequest: {
            /** Instrument */
            instrument: components["schemas"]["EuropeanOptionIn"] | components["schemas"]["AmericanOptionIn"] | components["schemas"]["DigitalOptionIn"];
            market: components["schemas"]["MarketIn"];
            /**
             * @default {
             *       "dividend_treatment": "escrowed",
             *       "type": "bsm"
             *     }
             */
            model?: components["schemas"]["ModelIn"];
            /**
             * @default {
             *       "bumps": {
             *         "rate_abs": 0.0001,
             *         "spot_rel": 0.001,
             *         "time_days": 1,
             *         "vol_abs": 0.001
             *       },
             *       "digital": {
             *         "spread_width_rel": 0.01
             *       },
             *       "force_bump_greeks": false,
             *       "implied_vol": {
             *         "max_iterations": 2
             *       },
             *       "pde": {
             *         "n_std": 5,
             *         "penalty": 100000000,
             *         "penalty_max_iter": 25,
             *         "penalty_tol": 1e-12,
             *         "rannacher_steps": 2,
             *         "space_nodes": 800,
             *         "time_steps": 200
             *       },
             *       "scenario": {
             *         "pde_space_nodes": 200,
             *         "pde_time_steps": 100,
             *         "tree_steps": 101
             *       },
             *       "tree": {
             *         "steps": 401
             *       }
             *     }
             */
            settings?: components["schemas"]["SettingsIn"];
            /**
             * Target Price
             * @description Unit price, currency
             */
            target_price: number;
        };
        /**
         * ImpliedVolResponse
         * @description Implied vol and the quantities it was solved from.
         */
        ImpliedVolResponse: {
            /** Discount Factor */
            discount_factor: number;
            /** Forward */
            forward: number;
            /**
             * Implied Vol
             * @description Decimal
             */
            implied_vol: number;
            /** Time To Expiry */
            time_to_expiry: number;
        };
        /**
         * ImpliedVolSettingsIn
         * @description Implied-vol solver settings.
         */
        ImpliedVolSettingsIn: {
            /**
             * Max Iterations
             * @default 2
             */
            max_iterations?: number;
        };
        /**
         * MarketIn
         * @description Market snapshot. Each rate is a flat decimal or a pillar curve.
         *
         *     Under Black-76, ``spot`` is the forward (futures) price for the option expiry and the
         *     dividend yield, borrow and discrete dividends are ignored.
         */
        MarketIn: {
            /**
             * Borrow
             * @description Repo/borrow spread(s), continuous
             * @default 0
             */
            borrow?: number | components["schemas"]["CurveIn"];
            /**
             * Dividend Yield
             * @description Continuous dividend yield(s)
             * @default 0
             */
            dividend_yield?: number | components["schemas"]["CurveIn"];
            /**
             * Dividends
             * @default []
             */
            dividends?: components["schemas"]["DividendIn"][];
            /**
             * Rate
             * @description Discount zero rate(s), continuous
             */
            rate: number | components["schemas"]["CurveIn"];
            /** Spot */
            spot: number;
            /**
             * Valuation Date
             * Format: date
             */
            valuation_date: string;
            /**
             * Vol
             * @description Implied volatility, decimal
             */
            vol: number;
        };
        /**
         * MetaResponse
         * @description Static metadata for the UI.
         */
        MetaResponse: {
            /** Methods */
            methods: components["schemas"]["MethodOut"][];
            /** Version */
            version: string;
        };
        /**
         * MethodComparison
         * @description One method's result, or why it cannot price this product.
         */
        MethodComparison: {
            /**
             * Convergence
             * @default []
             */
            convergence?: components["schemas"]["ConvergencePointOut"][];
            /** Error */
            error?: string | null;
            /**
             * Greeks
             * @description Cash greeks
             */
            greeks?: components["schemas"]["GreekOut"][] | null;
            /** Label */
            label: string;
            /** Method */
            method: string;
            /**
             * Price
             * @description Unit price, currency
             */
            price?: number | null;
            /**
             * Resolution
             * @description Tree steps or PDE space nodes
             */
            resolution?: number | null;
            /** Runtime Ms */
            runtime_ms?: number | null;
            /** Supported */
            supported: boolean;
        };
        /**
         * MethodOut
         * @description A registered pricing method and the products it supports.
         */
        MethodOut: {
            /** Instruments */
            instruments: ("european" | "american" | "digital")[];
            /** Label */
            label: string;
            /** Name */
            name: string;
        };
        /**
         * ModelIn
         * @description Model selection.
         */
        ModelIn: {
            /**
             * @description BSM cash dividends: escrowed (lognormal S − PV) or spot jumps (PDE only)
             * @default escrowed
             */
            dividend_treatment?: components["schemas"]["DividendTreatment"];
            /**
             * Type
             * @default bsm
             * @enum {string}
             */
            type?: "bsm" | "black76";
        };
        /**
         * OptionType
         * @description Call or put. ``omega`` is +1 for a call and −1 for a put.
         * @enum {string}
         */
        OptionType: "call" | "put";
        /**
         * PdeSettingsIn
         * @description Crank–Nicolson PDE.
         */
        PdeSettingsIn: {
            /**
             * N Std
             * @default 5
             */
            n_std?: number;
            /**
             * Penalty
             * @default 100000000
             */
            penalty?: number;
            /**
             * Penalty Max Iter
             * @default 25
             */
            penalty_max_iter?: number;
            /**
             * Penalty Tol
             * @default 1e-12
             */
            penalty_tol?: number;
            /**
             * Rannacher Steps
             * @default 2
             */
            rannacher_steps?: number;
            /**
             * Space Nodes
             * @default 800
             */
            space_nodes?: number;
            /**
             * Time Steps
             * @default 200
             */
            time_steps?: number;
        };
        /**
         * PillarIn
         * @description Continuously compounded zero rate to ``date`` (ACT/365F from the valuation date).
         */
        PillarIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rate */
            rate: number;
        };
        /**
         * PriceRequest
         * @description Price one instrument.
         */
        PriceRequest: {
            /** Instrument */
            instrument: components["schemas"]["EuropeanOptionIn"] | components["schemas"]["AmericanOptionIn"] | components["schemas"]["DigitalOptionIn"];
            market: components["schemas"]["MarketIn"];
            /**
             * Method
             * @default analytic
             */
            method?: string;
            /**
             * @default {
             *       "dividend_treatment": "escrowed",
             *       "type": "bsm"
             *     }
             */
            model?: components["schemas"]["ModelIn"];
            /**
             * @default {
             *       "bumps": {
             *         "rate_abs": 0.0001,
             *         "spot_rel": 0.001,
             *         "time_days": 1,
             *         "vol_abs": 0.001
             *       },
             *       "digital": {
             *         "spread_width_rel": 0.01
             *       },
             *       "force_bump_greeks": false,
             *       "implied_vol": {
             *         "max_iterations": 2
             *       },
             *       "pde": {
             *         "n_std": 5,
             *         "penalty": 100000000,
             *         "penalty_max_iter": 25,
             *         "penalty_tol": 1e-12,
             *         "rannacher_steps": 2,
             *         "space_nodes": 800,
             *         "time_steps": 200
             *       },
             *       "scenario": {
             *         "pde_space_nodes": 200,
             *         "pde_time_steps": 100,
             *         "tree_steps": 101
             *       },
             *       "tree": {
             *         "steps": 401
             *       }
             *     }
             */
            settings?: components["schemas"]["SettingsIn"];
        };
        /**
         * PriceResponse
         * @description Price, market-derived quantities, greeks and diagnostics.
         */
        PriceResponse: {
            /** Currency */
            currency: string;
            diagnostics: components["schemas"]["DiagnosticsOut"];
            /** Discount Factor */
            discount_factor: number;
            /**
             * Forward
             * @description Model forward to expiry, including discrete dividends
             */
            forward: number;
            greeks: components["schemas"]["GreeksOut"];
            /**
             * Notional
             * @description quantity × spot, currency
             */
            notional: number;
            /**
             * Pct Notional
             * @description 100 × unit price / spot, %
             */
            pct_notional: number;
            /**
             * Position Value
             * @description quantity × unit price, currency
             */
            position_value: number;
            /**
             * Price
             * @description Unit price, currency
             */
            price: number;
            /**
             * Time To Expiry
             * @description ACT/365F year fraction
             */
            time_to_expiry: number;
        };
        /**
         * ProfileRequest
         * @description Price and greeks along spot (at several horizons) or along time (at several spot shifts).
         */
        ProfileRequest: {
            /**
             * Axis
             * @enum {string}
             */
            axis: "spot" | "time";
            /**
             * Greeks
             * @description Greeks to compute (default all; [] for value only)
             */
            greeks?: components["schemas"]["Greek"][] | null;
            /**
             * Horizons Days
             * @description Spot axis: valuation-date rolls
             * @default [
             *       0
             *     ]
             */
            horizons_days?: number[];
            /**
             * Points
             * @default 81
             */
            points?: number;
            pricing: components["schemas"]["PriceRequest"];
            /**
             * Spot Range Pct
             * @description Spot axis: ±range, %
             * @default 30
             */
            spot_range_pct?: number;
            /**
             * Spot Shifts Pct
             * @description Time axis: spot shifts, %
             * @default [
             *       0
             *     ]
             */
            spot_shifts_pct?: number[];
        };
        /**
         * ProfileResponse
         * @description Profiles along spot or time.
         */
        ProfileResponse: {
            /**
             * Axis
             * @enum {string}
             */
            axis: "spot" | "time";
            /** Currency */
            currency: string;
            /**
             * Notional
             * @description quantity × current spot, currency
             */
            notional: number;
            /**
             * Payoff
             * @description Spot axis: position payoff at expiry
             */
            payoff: number[] | null;
            /** Series */
            series: components["schemas"]["ProfileSeries"][];
            /** Spot */
            spot: number;
            /** Strike */
            strike: number;
            /** Units */
            units: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /**
             * X
             * @description Spot level, or days to expiry
             */
            x: number[];
        };
        /**
         * ProfileSeries
         * @description One line family of a profile: value and greeks along the x axis.
         */
        ProfileSeries: {
            /** Greeks */
            greeks: {
                [key: string]: {
                    [key: string]: number[];
                };
            };
            /** Horizon Days */
            horizon_days: number;
            /** Label */
            label: string;
            /** Position Value */
            position_value: number[];
            /** Spot Shift Pct */
            spot_shift_pct: number;
        };
        /**
         * ScenarioSettingsIn
         * @description Numerical-method resolution for charts.
         */
        ScenarioSettingsIn: {
            /**
             * Pde Space Nodes
             * @default 200
             */
            pde_space_nodes?: number;
            /**
             * Pde Time Steps
             * @default 100
             */
            pde_time_steps?: number;
            /**
             * Tree Steps
             * @default 101
             */
            tree_steps?: number;
        };
        /**
         * SettingsIn
         * @description Numerical settings.
         */
        SettingsIn: {
            /**
             * @default {
             *       "rate_abs": 0.0001,
             *       "spot_rel": 0.001,
             *       "time_days": 1,
             *       "vol_abs": 0.001
             *     }
             */
            bumps?: components["schemas"]["BumpSettingsIn"];
            /**
             * @default {
             *       "spread_width_rel": 0.01
             *     }
             */
            digital?: components["schemas"]["DigitalSettingsIn"];
            /**
             * Force Bump Greeks
             * @description Bump-and-revalue every greek, even where closed forms exist
             * @default false
             */
            force_bump_greeks?: boolean;
            /**
             * @default {
             *       "max_iterations": 2
             *     }
             */
            implied_vol?: components["schemas"]["ImpliedVolSettingsIn"];
            /**
             * @default {
             *       "n_std": 5,
             *       "penalty": 100000000,
             *       "penalty_max_iter": 25,
             *       "penalty_tol": 1e-12,
             *       "rannacher_steps": 2,
             *       "space_nodes": 800,
             *       "time_steps": 200
             *     }
             */
            pde?: components["schemas"]["PdeSettingsIn"];
            /**
             * @default {
             *       "pde_space_nodes": 200,
             *       "pde_time_steps": 100,
             *       "tree_steps": 101
             *     }
             */
            scenario?: components["schemas"]["ScenarioSettingsIn"];
            /**
             * @default {
             *       "steps": 401
             *     }
             */
            tree?: components["schemas"]["TreeSettingsIn"];
        };
        /**
         * TreeSettingsIn
         * @description Leisen–Reimer tree.
         */
        TreeSettingsIn: {
            /**
             * Steps
             * @description Odd
             * @default 401
             */
            steps?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_api_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    heatmap_api_heatmap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeatmapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    implied_vol_api_implied_vol_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpliedVolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpliedVolResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    price_api_price_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_api_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
